### ISSUE TITLE
Non-Functional

### ISSUE THREAD

**Issue by imakunee** [GraysonnG/RelicSorter#1]
Doesn't seem to be working at all with ModTheSpire 3.1.0, and BaseMod 3.2.2. Right clicking a relic has no effect on the order the relics are displayed. I look forward to an update to fix this as it's very useful for relics that have stacking effects to be on the same page. Thank you very much for your work on this mod!

**Comment by KongMD-Steam** [comment]
@imakunee It does function, but only in combat. If you try to sort outside of combat, it won't sort your relics.
