### ISSUE TITLE
soft lock with this mod

### ISSUE THREAD

**Issue by oncmonkey** [GraysonnG/RelicSorter#2]
after about 3-6 rooms ill get a reward screen that just soft locks the game to the point where i gotta alt f4 to get out
is repeatable have reinstalled the mod have resorted my mod order (copied rhapsodys) and it only happens when i have this mod enabled (have gone through 1 by 1 to test to see which one causes it and its only this one)

1 more test was removing the mod and loading a save... still soft locked not shocked but just informin

**Comment by GraysonnG** [comment]
Can you post a log from one of the times this happened.
